//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Models {
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Contrato {
        [IgnoreDataMember]
        public int Id { get; set; }
        public long CpfCliente { get; set; }
        public int IdVeiculo { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public float Valor { get; set; }
    }
}
