//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Models {
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Login {
        public int Id { get; set; }
        public string Usuario { get; set; }
        [IgnoreDataMember]
        public string Senha { get; set; }
        public string Tipo { get; set; }
    }
}
