//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Models {
    using System;
    using System.Collections.Generic;

    public partial class Veiculo {
        /// <summary>
        /// Id do veículo
        /// </summary>
        public int Id { get; set; }
        public string Placa { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
        public float ValorDiaria { get; set; }
        public long Kilometragem { get; set; }
        public bool Status { get; set; }
    }
}
