USE [master]
GO

/****** Object:  Database [EnterpriseDatabase]    Script Date: 28/09/2021 00:54:45 ******/
CREATE DATABASE [EnterpriseDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EnterpriseDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EnterpriseDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EnterpriseDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EnterpriseDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EnterpriseDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EnterpriseDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EnterpriseDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EnterpriseDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EnterpriseDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EnterpriseDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EnterpriseDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [EnterpriseDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EnterpriseDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EnterpriseDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EnterpriseDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EnterpriseDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EnterpriseDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EnterpriseDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EnterpriseDatabase] SET  READ_WRITE 
GO


